image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  REPOSITORY: $CI_REGISTRY/mthaithanh/growbox

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -f Dockerfile -t $REPOSITORY:latest .
    - docker push $REPOSITORY:latest
  only:
    - master